version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app_container
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_KEY: ${APP_KEY}
    depends_on:
      - composer

  composer:
    image: composer:2
    container_name: composer_container
    working_dir: /app
    volumes:
      - .:/app
    command: install --ignore-platform-reqs

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html:cached
    depends_on:
      - app

networks:
  default:
    name: laravel
